############################
## CHANGE THESE
############################

baseURL: "https://ivstrook.github.io/ivs20250809"
title: ivs20250809

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
