###########################
## CHANGE THESE
############################

baseURL: "https://ivstrook.tech"
title: ivstrook

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "ja-jp"
enableRobotsTXT: true
