############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: Blog
  url: /blog/
  weight: 20
- name: History
  url: /history/
  weight: 25
- name: About
  url: /about/
  weight: 30
