############################
## Navbar
############################

main:
- name: 新しい記事
  url: /blog/xperia/
  weight: 5
- name: Home
  url: /
  weight: 10
- name: Blog
  url: /blog/
  weight: 20
- name: About
  url: /about/
  weight: 30
