############################
## Author
############################

author:
  name: フェゼレント（ivstrook）
  image: author.png
  greeting: "2025/8/12 記事を公開しました"
  icon: ":turtle:"

############################
## Links
############################

links:
  - github: https://github.com/ivstrook/ivs20250809
  - x-twitter: https://x.com/ShibaSmile_Love
  - mastodon: https://mstdn.social/@ivstrook
  - reddit: https://reddit.com/u/ivstrook 
  - email: mailto:jardsocial@proton.me
  - discord: https://discordapp.com/users/1138032005762781204
  - soundcloud: https://soundcloud.com/underground-re-store
  - bluesky:  https://bsky.app/profile/ivstrook.bsky.social
  - spotify: https://open.spotify.com/user/pbvovtf7ifvzhm4hxfdo26l2v?si=105ee119cbe144b5
###############################
## OpenGraph & Twitter Cards ##
###############################

title: ivstrook Homepage
description: "Site build with Qubt & Hugo"
images:
  - thumbnail.png