############################
## Author
############################
author:
  name: ivstrook
  image: author.png
  greeting: "Chill out,Always."
  icon: ":palm_tree:"
  info: ""

###############################
## OpenGraph & Twitter Cards ##
###############################

title: ivstrook Homepage
description: "Site build with Qubt & Hugo"
images:
  - thumbnail.png
  